// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fabioods/go-expert-call-weather/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// WeatherByCepClient is an autogenerated mock type for the WeatherByCepClient type
type WeatherByCepClient struct {
	mock.Mock
}

// WeatherByCep provides a mock function with given fields: ctx, cep
func (_m *WeatherByCepClient) WeatherByCep(ctx context.Context, cep string) (domain.Cep, error) {
	ret := _m.Called(ctx, cep)

	if len(ret) == 0 {
		panic("no return value specified for WeatherByCep")
	}

	var r0 domain.Cep
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Cep, error)); ok {
		return rf(ctx, cep)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Cep); ok {
		r0 = rf(ctx, cep)
	} else {
		r0 = ret.Get(0).(domain.Cep)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cep)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWeatherByCepClient creates a new instance of WeatherByCepClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherByCepClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherByCepClient {
	mock := &WeatherByCepClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
