services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
      
  call-weather:
    container_name: call-weather
    build: 
      context: ./call-weather
    depends_on:
      - jaeger-all-in-one
      - otel-collector
      - weather-lab
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_URL=http://weather-lab:8080/weather/cep
      - WEATHER_API_TIMEOUT=5000
      - PORT=8081
      - OTEL_SERVICE_NAME=call-weather
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - REQUEST_NAME_OTEL=call-weather

  weather-lab:
    container_name: weather-lab
    build: 
      context: ./weather-lab
    depends_on:
      - jaeger-all-in-one
      - otel-collector
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_URL=https://api.weatherapi.com/v1/current.json
      - WEATHER_API_TIMEOUT=5000
      - WEATHER_API_KEY=368822d6298c48859bb02606242610
      - PORT=8080
      - OTEL_SERVICE_NAME=weather-app
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - REQUEST_NAME_OTEL=weather-app
      - CEP_API_URL=https://viacep.com.br/ws/
      - CEP_API_TIMEOUT=1000
    